name: DEPLOY TO PRODUCTION

on:
  push:
    branches:
      - master

jobs:
  cyon-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
      - name: Installing project dependencies
      - run: npm install
      - name: Building the project
      - run: npm run build
        env:
          FIREBASE_APPCHECK_DEBUG_TOKEN: ${{ secrets.FIREBASE_APPCHECK_DEBUG_TOKEN }}