name: BUILD FOR PRODUCTION AND DEPLOY ON FIREBASE

on:
  push:
    branches:
      - master

jobs:
  build_and_deploy_firebase:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Installing & Building the project
        run: npm ci && npm run build
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_ALL_IN_ONE_FITNESS_B99D0 }}'
          projectId: all-in-one-fitness-b99d0
          channelId: live